### PR TITLE
Add python file to executables files

### PR DESCRIPTION
**Pull request by obazoud**

### CODE REVIEW

**Comment by eheydrick** [comment]
This will drop a ruby binstub in the bin directory but you won't be able to run it because it'll try to execute the python with ruby. I think we need to provide a ruby wrapper for python scripts that exec's them. We need to fix this for the several repos that have python plugins.

**Comment by obazoud** [comment]
workaround found ?
This PR works fine here ;)

**Comment by mattyjones** [comment]
This breaks gem conventions. I would rather see something in the build pipeline that dropped a shell stub for all non .rb plugins.

**Comment by obazoud** [comment]
any news ?

**Comment by mattyjones** [comment]
@obazoud  I added a binstub manually for this.

**Comment by obazoud** [comment]
@mattyjones I upgrade to 0.3.0 and unfortunately it is buggy. Couchbase metric is a python script not a shell see #6

**Comment by mattyjones** [comment]
@obazoud releasing a new version right now 1.0.0 (dropping support for Rubies 1.9.3 and 2.0 and adding support for 2.3

**Comment by obazoud** [comment]
Thanks @mattyjones !

**Pull request closed without merging**
